#!/bin/sh /etc/rc.common

START=99

network_ifstatus_monitor ()
{
    while true; do
        if [ -z "$(cat /var/xq3/net_register_state | grep MIPC_NW_REGISTER_STATE_HOME)" ]; then
            echo -n 0 > /var/xq3/net_ifstatus_state
            sleep 2
            continue
        fi

        if [ -z "$(ifstatus wan | grep up | grep true)"  ]; then
            echo -n 0 > /var/xq3/net_ifstatus_state
            sleep 2
            continue
        fi

        cur_ip="$(ifstatus wan | grep \"address\" | cut -d'"' -f4 )"
        if [ "$cur_ip" == "" ]; then
            echo -n 1 > /var/xq3/net_ifstatus_state
        else
            echo -n $cur_ip > /var/xq3/net_ifstatus_state
        fi

        sleep 2
    done
}

network_md_monitor ()
{
    while true; do
        tmp=$(mipc_wan2_cli --show_register_status | sed 's/\r$//')
        echo -n "$tmp" > /var/xq3/net_register_state
        sleep 1
        tmp=$(mipc_wan2_cli --at_cmd AT+EDMFAPP=6,13,11 | grep "AT res" | sed 's/\r$//')
        echo -n "$tmp" > /var/xq3/net_EDMFAPP_6_13_11
        sleep 1
    done
}

start()
{
    mkdir /data/xq3
    mkdir /var/xq3
    tmp=$(mipc_wan2_cli --at_cmd AT+EGMR=0,7 | grep "AT res" | awk -F'"' '{print $2}' | sed 's/\r$//')
    echo -n "$tmp" > /var/xq3/imei
    echo -n 0 > /var/xq3/net_ifstatus_state
    echo -n UNKNOWN > /var/xq3/net_register_state

    # disable WU9 wifi
    /usr/bin/nxp_wifi_power_off.sh

    # run daemon
    network_ifstatus_monitor &
    network_md_monitor &
}
